# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
user = User.create(email: 'user1@test', password: 'password', password_confirmation: 'password')

cut__by_wolfgang_puck_owner = Owner.create(email: 'owner1@test', password: 'password', password_confirmation: 'password' );

cut__by_wolfgang_puck = Restaurant.create(name: "Cut By Wolfgang Puck", image_url:"https://rrsg.s3.amazonaws.com/wp-content/uploads/2018/09/22191311/FEATcut_MAIN.jpg", owner_id: cut__by_wolfgang_puck_owner.id)


open_farm_community = Restaurant.create(name:"Open Farm Community",image_url:"https://d22ir9aoo7cbf6.cloudfront.net/wp-content/uploads/sites/2/2017/11/Kampung-French-OFC-mussels-Honeycombers-Singapore.jpg", owner_id: cut__by_wolfgang_puck_owner.id)

Food.create([{name: "Watercress soup, soft organic egg, crispy kale, pita bread", restaurant_id: open_farm_community.id}, {name:
"Warm salad of broccolu, pine nuts, sugar snap peas, crumbled feta", restaurant_id: open_farm_community.id}, {name: "Garden pea soup, garden knife beans, jamon, super snap peas, pita bread", restaurant_id: open_farm_community.id}, {name: "Crispy Jurong frog legs, root vegetables & lemak inspired curry, garden curry leaves", restaurant_id: open_farm_community.id}, {name: "Steak tartare marinared with ginger chill, spring onion & coriander puree, garlic crouton, organic egg yolk ", restaurant_id: open_farm_community.id},{name: "Roasted king prawns, garden herb gremolata, compressed spring onions", restaurant_id: open_farm_community.id}, {name: "Coconut laksa barramundi, turmeric potato cake, baby bok choy", restaurant_id:open_farm_community.id},{name: "Red grouper burger, chucky tar tar sauce, picked cucumber, local green salad", restaurant_id: open_farm_community.id}, {name: "Roasted red snapper, calamansi & sasame cucumber salad, garden roselle & hibiscus ketchup pickled cucumber", restaurant_id: open_farm_community.id}, {name: "Braised lamb shank, homemade couscous, olives, capers, garden peas", restaurant_id: open_farm_community.id}, {name: "BBQ half chicken, sweet corn ragout, potato fondant, mustard frill salad", restaurant_id: open_farm_community.id}, {name:"Yogurt & southern woord dressed cauliflower, cumin, spiced pan crystal", restaurant_id: open_farm_community.id}, {name:"Local snake bean, abalone mushroom, fermented sugar cane dressing", restaurant_id: open_farm_community.id}, {name:"Smoked paprika buttered sweet corn, salted caramel popcorn, chimichurri", restaurant_id: open_farm_community.id}, {name:"Garden holy basil gnocchi, pickled okra, lemon grass dressing", restaurant_id:open_farm_community.id}, {name:"Rigatoni, local mushrooms, smoked pancetta, stilton, balsamic graze", restaurant_id: open_farm_community.id}, {name: "Saffron carnaroli risotto, chorizo, cuttlefish, green peas, crispy Serrano, ebi", restaurant_id:open_farm_community.id}, {name:
"48 hour Barolo braised oxtail strozzapreti, parmesan wafers, garden thyme", restaurant_id: open_farm_community.id}, {name:"Baby Caesar salad, poached chicken breast", restaurant_id: open_farm_community.id}, {name: "strozzapreti, tomato sauce, fresh sweet basil", restaurant_id: open_farm_community.id}, {name: "Rustic fish pie, fresh thyme from the garden", restaurant_id: open_farm_community.id}, {name: "Open-face lasagna, beef bolognese, bechamel", restaurant_id: open_farm_community.id}, {name: "Homemade trio of ice cream, sable cookies", restaurant_id:open_farm_community.id}, {name:"Pandan & banana custard, ginger biscuit, lemon grass sago, sugar cane sorbet", restaurant_id: open_farm_community.id},{name:"Caramalised mango, textires of coconut", restaurant_id: open_farm_community.id}, {name:"Lemon tart, sweet basil ice cream", restaurant_id: open_farm_community.id},{name:"Selection of matured cheese & condiments", restaurant_id: open_farm_community.id}])